apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo-file-deployment
spec:
  selector:
    matchLabels:
      app: golang
  replicas: 1
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: go-test-app
        image: go-test-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
